
import React,{useEffect,useState} from 'react';
import {Home,BookOpen,MessageCircle,Briefcase,BarChart3,Volume2,ChevronRight,ChevronLeft,Check} from 'lucide-react';
import {CRASH_COURSE,REAL_LIFE_ROLEPLAYS,WORK_LESSONS,BERLITZ_PATH,BERLITZ_REINFORCEMENT} from './data/beginner';

const T={ground:'#0E2B2A',surface:'#143836',raised:'#1B4543',line:'#27544F',cream:'#F2E9DC',sand:'#BFAE97',marigold:'#E9A33C',jade:'#57B79A',rose:'#DB6A6A',violet:'#9B7BB8'};
const serif='Georgia,"Iowan Old Style","Times New Roman",serif';
const mono='ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
const sans='system-ui,-apple-system,"Segoe UI",Roboto,sans-serif';
const KEY='espanol:beginner:v14';

function useProgress(){
 const [state,setState]=useState({completed:{},scores:{},xp:0});
 useEffect(()=>{try{const r=localStorage.getItem(KEY);if(r)setState(JSON.parse(r))}catch{}},[]);
 const save=n=>{setState(n);try{localStorage.setItem(KEY,JSON.stringify(n))}catch{}};
 const complete=(id,score=100)=>save({...state,completed:{...state.completed,[id]:Date.now()},scores:{...state.scores,[id]:score},xp:state.xp+20});
 return {state,complete};
}
function say(text,rate=.86){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-GT';u.rate=rate;speechSynthesis.speak(u)}catch{}}
function norm(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function scoreAnswer(text,keys=[]){if(!text.trim())return 0;const n=norm(text),hits=keys.filter(k=>n.includes(norm(k))).length,words=text.trim().split(/\s+/).length;return Math.min(100,Math.round(Math.min(45,words*4)+(keys.length?hits/keys.length*55:45)))}
function Header({title,sub,onBack}){return <div style={{display:'flex',gap:10,alignItems:'center',padding:'24px 20px 14px'}}>{onBack&&<button onClick={onBack} style={{width:38,height:38,borderRadius:12,border:`1px solid ${T.line}`,background:T.surface,color:T.cream}}><ChevronLeft size={19}/></button>}<div><div style={{fontFamily:serif,fontSize:23}}>{title}</div>{sub&&<div style={{fontFamily:mono,fontSize:9.5,color:T.sand,letterSpacing:'.09em',marginTop:2}}>{sub.toUpperCase()}</div>}</div></div>}
function Bar({value,color=T.jade}){return <div style={{height:6,borderRadius:99,background:'rgba(242,233,220,.08)',overflow:'hidden'}}><div style={{height:'100%',width:`${value}%`,background:color,borderRadius:99}}/></div>}

function HomePage({progress,onGo}){
 const all=CRASH_COURSE.flatMap(c=>c.lessons.map(l=>`${c.id}:${l.id}`)),done=all.filter(id=>progress.state.completed[id]).length,pct=Math.round(done/all.length*100);
 let next=null;for(const c of CRASH_COURSE){for(const l of c.lessons){if(!progress.state.completed[`${c.id}:${l.id}`]){next={c,l};break}}if(next)break}
 return <div style={{paddingBottom:28}}>
  <div style={{padding:'30px 20px 14px'}}><div style={{fontFamily:mono,fontSize:10,color:T.sand,letterSpacing:'.15em'}}>POCO A POCO · BEGINNER FIRST</div><div style={{fontFamily:serif,fontSize:38,lineHeight:1.05,marginTop:8}}>Spanish from zero<span style={{color:T.marigold}}>.</span></div><div style={{fontSize:13.5,color:T.sand,lineHeight:1.55,marginTop:9}}>No grammar knowledge assumed. Learn it, hear it, understand it, then use it.</div></div>
  <div style={{padding:'0 20px 10px'}}><div style={{background:T.surface,border:`1px solid ${T.marigold}`,borderRadius:18,padding:18}}><div style={{fontFamily:mono,fontSize:9,color:T.marigold}}>🚀 CRASH COURSE — START HERE</div><div style={{fontFamily:serif,fontSize:23,marginTop:7}}>{next?`Continue: ${next.c.title} → ${next.l.title}`:'Crash course complete'}</div><div style={{marginTop:12}}><Bar value={pct} color={T.marigold}/></div><div style={{display:'flex',justifyContent:'space-between',fontSize:11.5,color:T.sand,marginTop:5}}><span>{done} lessons completed</span><span>{pct}%</span></div><button onClick={()=>onGo('learn')} style={{width:'100%',padding:13,marginTop:13,borderRadius:13,border:0,background:T.marigold,color:T.ground,fontWeight:750}}>{next?'Continue learning':'Review course'}</button></div></div>
  <div style={{padding:'0 20px'}}>{[['practice','Practice',MessageCircle,T.jade,'Guided recall'],['life','Real Life',Home,T.violet,'Mercado · Vecino · Farmacia · Café · Uber'],['work','Work',Briefcase,T.rose,'Workplace Spanish when you are ready'],['progress','Progress',BarChart3,T.jade,'See your beginner roadmap']].map(([id,title,Icon,c,sub])=><button key={id} onClick={()=>onGo(id)} style={{width:'100%',padding:15,marginBottom:8,borderRadius:17,border:`1px solid ${T.line}`,background:T.surface,color:T.cream,textAlign:'left',display:'flex',alignItems:'center',gap:12}}><div style={{width:42,height:42,borderRadius:13,background:T.raised,display:'grid',placeItems:'center'}}><Icon size={20} color={c}/></div><div style={{flex:1}}><div style={{fontFamily:serif,fontSize:19}}>{title}</div><div style={{fontSize:12.5,color:T.sand,marginTop:2}}>{sub}</div></div><ChevronRight size={17} color={T.sand}/></button>)}</div>
 </div>
}

function LearnPage({progress}){
 const [mode,setMode]=useState('crash'),[cid,setCid]=useState(null),[lid,setLid]=useState(null),[berlitzUnit,setBerlitzUnit]=useState(null);
 const course=CRASH_COURSE.find(c=>c.id===cid),lesson=course?.lessons.find(l=>l.id===lid);
 const bu=BERLITZ_PATH.flatMap(s=>s.units).find(u=>u.n===berlitzUnit);

 if(bu){
   const reinforce=BERLITZ_REINFORCEMENT[bu.n]||[];
   return <><Header title={`Berlitz Unit ${bu.n}`} sub={bu.title} onBack={()=>setBerlitzUnit(null)}/><div style={{padding:'0 20px 28px'}}>
    <div style={{background:T.surface,border:`1px solid ${T.violet}`,borderRadius:16,padding:15,marginBottom:10}}>
      <div style={{fontFamily:mono,fontSize:9,color:T.violet}}>COMMUNICATION GOAL</div>
      <div style={{fontFamily:serif,fontSize:20,lineHeight:1.4,marginTop:7}}>{bu.goal}</div>
      <div style={{fontSize:12.5,color:T.sand,lineHeight:1.5,marginTop:9}}><b style={{color:T.cream}}>Language focus:</b> {bu.focus}</div>
      <div style={{fontSize:12.5,color:T.sand,lineHeight:1.5,marginTop:5}}><b style={{color:T.cream}}>Poco a Poco match:</b> {bu.match}</div>
    </div>
    {reinforce.length>0?<>{reinforce.map(([es,en])=><div key={es} style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:15,marginBottom:8}}><div style={{fontFamily:serif,fontSize:21}}>{es}</div><div style={{fontSize:12.5,color:T.sand,marginTop:5}}>{en}</div><button onClick={()=>say(es)} style={{width:'100%',padding:10,marginTop:9,borderRadius:11,border:`1px solid ${T.line}`,background:T.raised,color:T.cream}}><Volume2 size={16} style={{verticalAlign:'middle',marginRight:7}}/>Hear reinforcement</button></div>)}</>:<div style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:15,fontSize:13,color:T.sand,lineHeight:1.55}}>Use this unit as a checkpoint with your Berlitz Student Guide/audio, then return to the matched Poco a Poco module for extra practice.</div>}
    <div style={{background:'rgba(155,123,184,.08)',border:`1px solid ${T.violet}`,borderRadius:13,padding:12,marginTop:10,fontSize:11.5,color:T.sand,lineHeight:1.5}}>This app uses an original reinforcement summary mapped to your Berlitz Level 1 materials; the Berlitz book/audio files are not copied into the app.</div>
   </div></>;
 }

 if(lesson)return <><Header title={lesson.title} sub={`${course.title} · Learn → Hear → Understand`} onBack={()=>setLid(null)}/><div style={{padding:'0 20px 28px'}}>{lesson.note&&<div style={{background:T.surface,border:`1px solid ${T.violet}`,borderRadius:15,padding:14,marginBottom:9,fontSize:13,color:T.sand,lineHeight:1.55}}>{lesson.note}</div>}{lesson.phrases.map(([es,en])=><div key={es} style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:15,marginBottom:8}}><div style={{fontFamily:serif,fontSize:22,lineHeight:1.35}}>{es}</div><div style={{fontSize:13,color:T.sand,marginTop:5}}>{en}</div><button onClick={()=>say(es)} style={{width:'100%',padding:10,marginTop:10,borderRadius:12,border:`1px solid ${T.line}`,background:T.raised,color:T.cream}}><Volume2 size={16} style={{verticalAlign:'middle',marginRight:7}}/>Hear it</button></div>)}<button onClick={()=>{progress.complete(`${course.id}:${lesson.id}`);setLid(null)}} style={{width:'100%',padding:14,borderRadius:13,border:0,background:T.jade,color:T.ground,fontWeight:750}}><Check size={16} style={{verticalAlign:'middle',marginRight:7}}/>I understand this lesson</button></div></>;

 if(course)return <><Header title={course.title} sub={course.en} onBack={()=>setCid(null)}/><div style={{padding:'0 20px 28px'}}><div style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:15,marginBottom:10,fontSize:13.5,color:T.sand,lineHeight:1.55}}>{course.goal}</div>{course.lessons.map((l,i)=>{const done=progress.state.completed[`${course.id}:${l.id}`];return <button key={l.id} onClick={()=>setLid(l.id)} style={{width:'100%',padding:15,marginBottom:8,borderRadius:16,border:`1px solid ${done?T.jade:T.line}`,background:T.surface,color:T.cream,textAlign:'left',display:'flex',gap:10,alignItems:'center'}}><div style={{width:28,height:28,borderRadius:99,background:T.raised,display:'grid',placeItems:'center',color:done?T.jade:T.marigold}}>{done?<Check size={15}/>:i+1}</div><div style={{flex:1}}><div style={{fontFamily:serif,fontSize:18}}>{l.title}</div><div style={{fontSize:11.5,color:T.sand,marginTop:2}}>{l.phrases.length} phrases</div></div><ChevronRight size={17} color={T.sand}/></button>})}</div></>;

 return <><Header title="Learn" sub="Crash Course first · Berlitz reinforcement second"/><div style={{padding:'0 20px 28px'}}>
  <div style={{display:'flex',gap:7,marginBottom:11}}>
    <button onClick={()=>setMode('crash')} style={{flex:1,padding:10,borderRadius:11,border:`1px solid ${mode==='crash'?T.marigold:T.line}`,background:mode==='crash'?T.raised:'transparent',color:mode==='crash'?T.marigold:T.sand,fontFamily:mono,fontSize:9}}>CRASH COURSE</button>
    <button onClick={()=>setMode('berlitz')} style={{flex:1,padding:10,borderRadius:11,border:`1px solid ${mode==='berlitz'?T.violet:T.line}`,background:mode==='berlitz'?T.raised:'transparent',color:mode==='berlitz'?T.violet:T.sand,fontFamily:mono,fontSize:9}}>BERLITZ L1</button>
  </div>
  {mode==='crash'?CRASH_COURSE.map(c=>{const d=c.lessons.filter(l=>progress.state.completed[`${c.id}:${l.id}`]).length,p=Math.round(d/c.lessons.length*100);return <button key={c.id} onClick={()=>setCid(c.id)} style={{width:'100%',padding:15,marginBottom:8,borderRadius:17,border:`1px solid ${T.line}`,background:T.surface,color:T.cream,textAlign:'left',display:'flex',gap:12,alignItems:'center'}}><div style={{fontSize:29}}>{c.icon}</div><div style={{flex:1}}><div style={{fontFamily:serif,fontSize:19}}>{String(c.n).padStart(2,'0')} · {c.title}</div><div style={{fontSize:12.5,color:T.sand,margin:'3px 0 7px'}}>{c.en}</div><Bar value={p} color={p===100?T.jade:T.marigold}/></div><div style={{fontFamily:mono,fontSize:10,color:p===100?T.jade:T.sand}}>{p}%</div></button>}):<>
    <div style={{background:T.surface,border:`1px solid ${T.violet}`,borderRadius:16,padding:14,marginBottom:11,fontSize:12.5,color:T.sand,lineHeight:1.55}}>Mapped from your <b style={{color:T.cream}}>Berlitz Español 1 (A1)</b> materials. Use this as reinforcement alongside the Crash Course—not instead of it.</div>
    {BERLITZ_PATH.map(stage=><div key={stage.stage} style={{marginBottom:15}}><div style={{fontFamily:mono,fontSize:9,color:T.violet,letterSpacing:'.1em',margin:'0 0 7px'}}>{stage.stage.toUpperCase()}</div>{stage.units.map(u=><button key={u.n} onClick={()=>setBerlitzUnit(u.n)} style={{width:'100%',padding:13,marginBottom:6,borderRadius:15,border:`1px solid ${T.line}`,background:T.surface,color:T.cream,textAlign:'left',display:'flex',gap:10,alignItems:'center'}}><div style={{width:31,height:31,borderRadius:99,background:T.raised,display:'grid',placeItems:'center',fontFamily:mono,fontSize:9,color:T.violet}}>{u.n}</div><div style={{flex:1}}><div style={{fontFamily:serif,fontSize:17}}>{u.title}</div><div style={{fontSize:11.5,color:T.sand,marginTop:2}}>{u.match}</div></div><ChevronRight size={16} color={T.sand}/></button>)}</div>)}
  </>}
 </div></>;
}
function PracticePage(){
 const items=CRASH_COURSE.flatMap(c=>c.lessons.flatMap(l=>l.phrases.map(p=>({c,l,p}))));
 const [i,setI]=useState(0),[show,setShow]=useState(false);const x=items[i%items.length];
 return <><Header title="Practice" sub="Simple recall, not a test"/><div style={{padding:'0 20px 28px'}}><div style={{background:T.surface,border:`1px solid ${T.jade}`,borderRadius:18,padding:20,textAlign:'center'}}><div style={{fontFamily:mono,fontSize:9,color:T.sand}}>{x.c.title.toUpperCase()}</div><div style={{fontSize:13,color:T.sand,marginTop:12}}>How would you say:</div><div style={{fontFamily:serif,fontSize:25,lineHeight:1.35,marginTop:7}}>{x.p[1]}</div>{show&&<><div style={{fontFamily:serif,fontSize:28,color:T.marigold,marginTop:18}}>{x.p[0]}</div><button onClick={()=>say(x.p[0])} style={{width:'100%',padding:11,marginTop:10,borderRadius:12,border:`1px solid ${T.line}`,background:T.raised,color:T.cream}}><Volume2 size={16} style={{verticalAlign:'middle',marginRight:7}}/>Hear answer</button></>}<button onClick={()=>show?(setI(i+1),setShow(false)):setShow(true)} style={{width:'100%',padding:13,marginTop:12,borderRadius:13,border:0,background:T.jade,color:T.ground,fontWeight:750}}>{show?'Next':'Show me'}</button></div></div></>;
}

function RealLifePage({progress}){
 const [id,setId]=useState(null),[turn,setTurn]=useState(0),[answer,setAnswer]=useState(''),[result,setResult]=useState(null);const s=REAL_LIFE_ROLEPLAYS.find(x=>x.id===id),q=s?.turns?.[turn];
 if(!s)return <><Header title="Real Life" sub="Use Spanish after learning the basics"/><div style={{padding:'0 20px 28px'}}>{REAL_LIFE_ROLEPLAYS.map(x=><button key={x.id} onClick={()=>{setId(x.id);setTurn(0)}} style={{width:'100%',padding:16,marginBottom:8,borderRadius:17,border:`1px solid ${T.line}`,background:T.surface,color:T.cream,textAlign:'left',display:'flex',gap:12}}><div style={{fontSize:30}}>{x.icon}</div><div><div style={{fontFamily:serif,fontSize:19}}>{x.title}</div><div style={{fontSize:12.5,color:T.sand,marginTop:3}}>{x.en} · {x.intro}</div></div></button>)}</div></>;
 if(!q)return <><Header title={s.title} sub="Roleplay complete" onBack={()=>setId(null)}/><div style={{padding:'0 20px'}}><div style={{background:T.surface,border:`1px solid ${T.jade}`,borderRadius:18,padding:22,textAlign:'center'}}><div style={{fontSize:44}}>{s.icon}</div><div style={{fontFamily:serif,fontSize:25,marginTop:8}}>You completed it</div><button onClick={()=>{setTurn(0);setAnswer('');setResult(null)}} style={{width:'100%',padding:13,marginTop:13,borderRadius:13,border:0,background:T.jade,color:T.ground,fontWeight:750}}>Repeat</button></div></div></>;
 const submit=()=>{const score=scoreAnswer(answer,q[2]);setResult({score,model:q[3]});progress.complete(`roleplay:${s.id}:${turn}`,score);say(q[3])};
 return <><Header title={`${s.icon} ${s.title}`} sub={`Turn ${turn+1} of ${s.turns.length}`} onBack={()=>setId(null)}/><div style={{padding:'0 20px 28px'}}><div style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:16}}><div style={{fontFamily:mono,fontSize:9,color:T.violet}}>{q[0].toUpperCase()}</div><div style={{fontFamily:serif,fontSize:22,marginTop:7}}>{q[1]}</div><button onClick={()=>say(q[1])} style={{marginTop:10,padding:9,borderRadius:99,border:`1px solid ${T.line}`,background:T.raised,color:T.cream}}><Volume2 size={17}/></button></div><div style={{background:T.raised,border:`1px solid ${T.line}`,borderRadius:16,padding:16,marginTop:9}}><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Answer in Spanish. Keep it simple…" style={{width:'100%',boxSizing:'border-box',minHeight:88,padding:12,borderRadius:12,border:`1px solid ${T.line}`,background:T.ground,color:T.cream,fontSize:16}}/><button onClick={submit} disabled={!answer.trim()||!!result} style={{width:'100%',padding:12,marginTop:8,borderRadius:12,border:0,background:answer.trim()&&!result?T.jade:T.surface,color:answer.trim()&&!result?T.ground:T.sand,fontWeight:700}}>Check</button></div>{result&&<div style={{background:T.surface,border:`1px solid ${result.score>=70?T.jade:T.marigold}`,borderRadius:16,padding:16,marginTop:9}}><div style={{fontFamily:serif,fontSize:30,color:result.score>=70?T.jade:T.marigold}}>{result.score}%</div><div style={{fontFamily:mono,fontSize:9,color:T.sand,marginTop:8}}>NATURAL MODEL</div><div style={{fontFamily:serif,fontSize:19,marginTop:5}}>{result.model}</div><button onClick={()=>{setTurn(turn+1);setAnswer('');setResult(null)}} style={{width:'100%',padding:12,marginTop:10,borderRadius:12,border:0,background:T.marigold,color:T.ground,fontWeight:750}}>Continue</button></div>}</div></>;
}

function WorkPage(){return <><Header title="Work Spanish" sub="Optional until you have the basics"/><div style={{padding:'0 20px 28px'}}><div style={{background:T.surface,border:`1px solid ${T.marigold}`,borderRadius:16,padding:15,marginBottom:10,fontSize:13,color:T.sand,lineHeight:1.55}}>This is deliberately secondary. Build your beginner foundation first.</div>{WORK_LESSONS.map(x=><div key={x.id} style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:15,marginBottom:8}}><div style={{fontFamily:serif,fontSize:19}}>{x.icon} {x.title}</div>{x.phrases.map(([es,en])=><div key={es} style={{padding:'10px 0',borderTop:`1px solid ${T.line}`}}><div style={{fontFamily:serif,fontSize:17}}>{es}</div><div style={{fontSize:12,color:T.sand,marginTop:2}}>{en}</div><button onClick={()=>say(es)} style={{marginTop:7,padding:'7px 10px',borderRadius:10,border:`1px solid ${T.line}`,background:T.raised,color:T.cream}}><Volume2 size={14}/></button></div>)}</div>)}</div></>}

function ProgressPage({progress}){const all=CRASH_COURSE.flatMap(c=>c.lessons.map(l=>`${c.id}:${l.id}`)),done=all.filter(id=>progress.state.completed[id]).length,pct=Math.round(done/all.length*100);return <><Header title="Progress" sub="Your beginner roadmap"/><div style={{padding:'0 20px 28px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9,marginBottom:10}}><div style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:14}}><div style={{fontFamily:mono,fontSize:9,color:T.sand}}>COURSE</div><div style={{fontFamily:serif,fontSize:28,marginTop:4}}>{pct}%</div></div><div style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:16,padding:14}}><div style={{fontFamily:mono,fontSize:9,color:T.sand}}>XP</div><div style={{fontFamily:serif,fontSize:28,marginTop:4}}>{progress.state.xp}</div></div></div>{CRASH_COURSE.map(c=>{const d=c.lessons.filter(l=>progress.state.completed[`${c.id}:${l.id}`]).length,p=Math.round(d/c.lessons.length*100);return <div key={c.id} style={{background:T.surface,border:`1px solid ${T.line}`,borderRadius:15,padding:13,marginBottom:7}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:6}}><span>{c.icon} {c.title}</span><span style={{fontFamily:mono,color:p===100?T.jade:T.marigold}}>{p}%</span></div><Bar value={p} color={p===100?T.jade:T.marigold}/></div>})}</div></>}

export default function App(){const progress=useProgress(),[tab,setTab]=useState('home');const nav=[['home','Home',Home],['learn','Learn',BookOpen],['practice','Practice',MessageCircle],['life','Real Life',Home],['work','Work',Briefcase],['progress','Progress',BarChart3]];const body=tab==='home'?<HomePage progress={progress} onGo={setTab}/>:tab==='learn'?<LearnPage progress={progress}/>:tab==='practice'?<PracticePage/>:tab==='life'?<RealLifePage progress={progress}/>:tab==='work'?<WorkPage/>:<ProgressPage progress={progress}/>;return <div style={{minHeight:'100vh',background:T.ground,color:T.cream,fontFamily:sans,paddingBottom:88}}><div style={{maxWidth:500,margin:'0 auto'}}>{body}</div><nav style={{position:'fixed',bottom:0,left:0,right:0,background:'rgba(14,43,42,.97)',borderTop:`1px solid ${T.line}`,backdropFilter:'blur(10px)'}}><div style={{maxWidth:500,margin:'0 auto',display:'flex'}}>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} style={{flex:1,padding:'11px 3px 17px',border:0,background:'transparent',color:tab===id?T.marigold:T.sand,display:'flex',flexDirection:'column',alignItems:'center',gap:4}}><Icon size={18}/><span style={{fontFamily:mono,fontSize:7.5}}>{label.toUpperCase()}</span></button>)}</div></nav></div>}
